import type { Metadata } from "next";
import "./globals.css";
 import "./style.css"

import Footer from "./footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CircleX Pvt Ltd",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          {children}
        </body>
      </html> */}

      <html data-theme="cupcake" lang="en">

      <body>
           {/* <Navbar /> */}
           <main className="h-[80%] flex justify-center">{children}</main>
          <Footer />

      </body>
          
       
       
      </html>
    </>
  );
}
